PROJECTNAME = $(shell basename "$(PWD)")

BINDIRECTORY = bin

REVISIONBRANCH = $(shell git rev-parse --abbrev-ref HEAD)
REVISIONCOMMIT = $(shell git rev-parse HEAD | head -c 8)
REVISIONDATE = $(shell date +%Y.%m.%d-%H:%M:%S)
REVISIONVERSION = $(shell git describe --tags $(shell git rev-list --tags --max-count=1))
REVISION = $(REVISIONBRANCH)-$(REVISIONCOMMIT)-$(REVISIONDATE)

LDFLAGS = -ldflags="-X main.revision=$(REVISION) -X main.version=$(REVISIONVERSION)"

BUILDFLAGS = -v

build:
	CGO_ENABLED=0 go build $(LDFLAGS) $(BUILDFLAGS) -o $(BINDIRECTORY)/anon-mail ./cmd/anon-mail/*.go

modules:
	go mod download

vendor:
	go mod vendor

codegen: vendor
	ifacemaker -f vendor/github.com/go-telegram-bot-api/telegram-bot-api/bot.go \
		-s BotAPI -i UCTelegramBotAPI -p anonbot \
		-y "UCTelegramBotAPI iterface for telegram bot api" \
		-c "DON'T EDIT: This code generated by ifacemaker. See Makefile codegen command!" \
		-o pkg/anonbot/tgapiiface.go

test:
	go test ./...

test.v:
	go test -v ./...

run: build
	$(BINDIRECTORY)/anon-mail

mock.generate: 
	mockery -name=Usecase -dir=pkg/msgsnd/ -output=pkg/msgsnd/ucmsgsnd/mocks
	mockery -name=Usecase -dir=pkg/chat/ -output=pkg/chat/ucchat/mocks

docker.run:
	docker-compose up -d anon-mail

docker.log:
	docker-compose logs -f

# docker.build:

# docker.deploy: docker.build

mock.generate:
	