// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/mavr/anonymous-mail/models"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetChatByUserUID provides a mock function with given fields: userUID
func (_m *Usecase) GetChatByUserUID(userUID string) (*models.Chat, error) {
	ret := _m.Called(userUID)

	var r0 *models.Chat
	if rf, ok := ret.Get(0).(func(string) *models.Chat); ok {
		r0 = rf(userUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewChatNotificate provides a mock function with given fields:
func (_m *Usecase) GetNewChatNotificate() (*models.Chat, error) {
	ret := _m.Called()

	var r0 *models.Chat
	if rf, ok := ret.Get(0).(func() *models.Chat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewChatNotificateChan provides a mock function with given fields:
func (_m *Usecase) GetNewChatNotificateChan() (<-chan *models.Chat, error) {
	ret := _m.Called()

	var r0 <-chan *models.Chat
	if rf, ok := ret.Get(0).(func() <-chan *models.Chat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *models.Chat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChatNotificate provides a mock function with given fields: c
func (_m *Usecase) NewChatNotificate(c *models.Chat) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Chat) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterPublisher provides a mock function with given fields:
func (_m *Usecase) RegisterPublisher() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterSubscriber provides a mock function with given fields:
func (_m *Usecase) RegisterSubscriber() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveNewChat provides a mock function with given fields: c
func (_m *Usecase) SaveNewChat(c *models.Chat) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Chat) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
